### ISSUE TITLE
Каждый должен УДАЛИТЬ свою ветку! СМ. КОММЕНТАРИИ

### ISSUE THREAD

**Issue by tokhichevsky** [python-am-cp/Ecosystem-of-information-bots#1]
Я так предполагаю, что мы будем работать каждый в своей ветке. Дойдя до какого-то законченного этапа (хорошо написанная функция и многие такие вещи), будем сливать (мержить/merge) **свои** ветки с **master** веткой через **pull request**. Надеюсь, все уже узнали, что такое pull request. Но вкратце, это запрос на слияние, который все мы должны будем одобрить или предложить правки и идеи. 
Почему так?

- Профессионалы делают так. У них обычно в master ветке всегда находится рабочее приложение, а все остальное разбито по другим веткам.

- Чтобы выдать комментарии и одобрение, нужно понимать, что происходит в коде, а чтобы понимать, что происходит, нужно понимать, как работают библиотеки и модули остальных разработчиков. Мы все здесь учимся, и как мне кажется, мы должны изучать и те библиотеки, с которыми, возможно, кто-то из нас сейчас работать не будет. 

- Комментарии других разработчиков могут быть полезны в обучении. Поскольку никто из нас не гуру пайтона и большинство видит некоторые библиотеки впервые, мы можем предложить друг другу неизвестные доселе более совершенные способы реализации каких-либо вещей. Например, люди привыкшие писать на языках типа C, C++, C#, Pascal привыкли использовать циклы и другие страшные вещи. Пайтон медленный язык и циклы не жалует, есть другие, более короткие и быстрые способы реализации таких действий. Друг разработчик, знающий о таких вещах, всегда подскажет, как сделать лучше.

Так что, давайте выполним нашу с вами первую задачу!

**Comment by svkov** [comment]
Насчет работы в отдельных ветках. Лучше делать новую ветку для каждого issue. В issue должны записываться задачи, кто-то может брать эти задачи на себя (в панельке справа assignees), и потом создавать пул реквест по этому issue (если пул реквест одобрили, issue можно закрывать)

**Comment by tokhichevsky** [comment]
Ну значит так)
