### ISSUE TITLE
Ошибка в схеме бд

### ISSUE THREAD

**Issue by Nikirovast** [python-am-cp/Ecosystem-of-information-bots#11]
Я решила сделать так: у каждого пользователя для каждой группы набор интересных тэгов. То есть стандартно он выбирает теги и они распространяются на все сообщества, но отдельно это можно изменить. Так вот там связь many to many, а у меня они в одной таблице. Как это лучше организовать все-таки? 
Святослав сказал мне, что в ORM Django ( возможно в Peewee тоже) можно все связи такого типа организовать без третьей таблицы. 
Но по идеи для красоты схемы лучше в одном стиле делать: если для всех связей выделяли таблицу, то и тут надо. Или убрать у всех. Жду вашего мнения.

**Comment by tokhichevsky** [comment]
Я бы использовал третью таблицу. Мы тогда сможем пересесть на любой фраемворк при желании, и у нас будет все работать из любого приложения на любом языке с любой библиотекой.

Я так-то не смотрел еще Peewee и Django, могу вообще ересь писать). У нас вроде кто-то должен был начать изучать их, пусть напишут, что думают.

**Comment by Nikirovast** [comment]
Я вспомнила, что у меня вчера такая идея была: primary key --  это groupid&userid, а дальше уже теги запихиваем в каждую группу и частоту. По умолчанию во все сообщества одни и те же теги пишем, дальше уже по желанию.

**Comment by tokhichevsky** [comment]
Не понял)
