### ISSUE TITLE
Конфликт

### ISSUE THREAD

**Issue by Nikirovast** [python-am-cp/Ecosystem-of-information-bots#15]
Переименуй файл "Ecosystem-of-information-bots" в папке неважных начальных действий, он создает конфликт, так как называется как папка.

**Comment by tokhichevsky** [comment]
Понял, принял, скоро исправлю

**Comment by svkov** [comment]
Про решение конфликтов можно отдельно еще почитать в той статье по гитхаб флоу (см. файлик с важной инфой, там есть ссылка)
